config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  mount Sidekiq::Web => '/sidekiq'

  get '/update_search', to: 'articles#update_search', as: :update_search
  get '/search_results', to: 'articles#search_results', as: :search_results

  resources :articles, only: [:index]
  post 'update_search_logs', to: "articles#update_search_logs", as: :update_search_logs
  root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/search_log.rb
class SearchLog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :get_articles, only: [:update_search_logs]
  before_action :get_ip_address, only: [:update_search, :search_results]


  def index
    response = ApiService.fetch_data
    if response.success?
      @articles = response.parsed_response.fetch("articles")
      @articles = @articles.select { |article| article.fetch("title")&.downcase&.include?(params[:search]&.downcase) } if params[:search].present?
    else 
      @error_message = "Error fetching data from the API: #{response.code}"
    end
  end

  def update_search_logs
    @query = params[:query]
    @articles = @articles.select { |article| article.fetch("title")&.downcase&.include?(@query&.downcase) } if @query.present?
    ActionCable.server.broadcast("SearchLogsChannel", { articles: @articles, query: @query })
    respond_to do |format|
      format.js
    end
  end

  def update_search
    query = {ip_address: @ip_address, search_query: params[:query]}
    #UpdateSearchLogsJob.perform_later(query) if query.present?
    ip_address = query.fetch(:ip_address)
    search_query = query.fetch(:search_query)

    SearchLog.create(ip_address: ip_address, search_query: search_query)
    head :no_content
  end

  def search_results
    @top_searches = SearchLog.group(:search_query).order('count_search_query DESC').limit(5).count(:search_query)
    @search_user_results = SearchLog.where(ip_address: @ip_address)
  end

  private 

  def get_articles
    response = ApiService.fetch_data
    if response.success?
      @articles = response.parsed_response.fetch("articles")
    else 
      @error_message = "Error fetching data from the API: #{response.code}"
    end
  end

  def get_ip_address
    ip = Socket.ip_address_list.detect{ |intf| intf.ipv4_private? }
    @ip_address = ip&.ip_address
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_articles.html.erb
<%= articles.each do |article| %>
  <div class="col-md-3 mb-3">
    <div class="card" style="">
      <img src="<%= article.fetch("urlToImage") %>" class="card-img-top" alt="<%= article.fetch("title") %>">
      <div class="card-body">
        <h5 class="card-title"><%= article.fetch("title") %></h5>
        <p class="card-text"><%= article.fetch("description") %></p>
        <a href="<%= article.fetch("url") %>" class="btn btn-primary" target="_blank">Read more...</a>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/index.html.erb
<div class="container-fluid p-5">
  <div class="row mb-5">
    <div class="col-md-6">
      <h1>Articles</h1>
    </div>
    <div class="col-md-3">
      <a href="<%= search_results_path %>" class="btn btn-info">Search results</a>
    </div>
    <div class="col-md-3">
      <div class="input-group">
        <%= form_with url: articles_path, method: :get, remote: true, class: "w-100" do %>
          <%= text_field_tag "search", nil, placeholder: "Search article by title", class: "form-control" %>
        <% end %>
      </div>
    </div>
  </div>
  <% if @error_message.present? %>
    <p><%= @error_message %></p>
  <% else %>
    <div class="row" id="remote_articles">
      <%= render "articles/articles", articles: @articles %>
    </div>
  <% end %>
</div>

app/views/articles/search_results.html.erb
<div class="container-fluid p-5">
  <div class="row mb-5">
    <div class="row">
      <div class="col-md-3">
        <a href="<%= articles_path %>" class="btn btn-info mb-3" id="back-link">Back</a>
      </div>
    </div>
    <div class="col-md-6">
      <h1>Top 5 User Searches</h1>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Number</th>
            <th scope="col">Searched Words</th>
            <th scope="col">Number of times Searched</th>
          </tr>
        </thead>
        <tbody>
          <% index = 0 %>
          <% @top_searches&.each do |query, count| %>
            <% index += 1 %>
            <tr>
              <td scope="row"><%= index %></td>
              <td><%= query %></td>
              <td><%= count %></td>
              </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-md-6">
      <h1>My Searches</h1>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Number</th>
            <th scope="col">Searched Words</th>
          </tr>
        </thead>
        <tbody>
          <% @search_user_results&.each&.with_index(1) do |query, index| %>
            <tr>
              <td scope="row"><%= index %></td>
              <td><%= query.search_query %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<script>
  document.getElementById('back-link').addEventListener('click', function(event) {
    event.preventDefault();
    setTimeout(function() {
      window.location.href = '<%= root_path %>';
    }, 100);
  });
</script>

app/views/articles/update_search_logs.js.erb
$("#remote_articles").html('<%= j render("articles/articles", articles: @articles) %>')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RealtimeSearch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>